import {
  Absorption,
  Diffusion,
  Liquid,
  Report,
  UnitQuestions,
  Sa7dan,
  UnitXuli2,
  Sheet1,
  Sheet2,
  Sheet3,
  Sheet4,
  ReactorQuestions,
  Heat1,
  Service,
  Solutions,
  BatchReactor,
  IndustryQuestions,
  Heat2025Q,
  HeatMarks1,
  HeatSa7dan,
  ModelL1,
  ModelL2,
  ModelL3,
  ModelL4,
  ModelOldQ,
  Model2025Q,
  ModelSa7dan,
  ModelMarks1,
  Eco2025Q,
  EcoOldQ,
  EcoMarks1,
  Plant2025Q,
  PlantMarks1,
  Shell,
  SingleCSTR,
  CSTRSeries,
  LD,
  LT,
  Laminar,
  Tubular,
  LabMarks1,
} from "../assets/semester5";

const unit = {
  id: 1,
  name: "unit",
  Absorption: Absorption,
  Diffusion: Diffusion,
  Liquid: Liquid,
  Report: Report,
  UnitQuestions,
  Sa7dan: Sa7dan,
  UnitXuli2: UnitXuli2,
};
const reactor = {
  id: 2,
  name: "reactor",
  Sheet1: Sheet1,
  Sheet2: Sheet2,
  Sheet3: Sheet3,
  Sheet4: Sheet4,
  ReactorQuestions: ReactorQuestions,
};
const lab3a = {
  id: 3,
  name: "lab3a",
  Heat1: Heat1,
  Service: Service,
  Solutions: Solutions,
  BatchReactor: BatchReactor,
};
const industry = {
  id: 4,
  name: "industry",
  IndustryQuestions: IndustryQuestions,
};
const heat = {
  id: 5,
  name: "heat",
  Heat2025Q: Heat2025Q,
  HeatMarks: HeatMarks1,
  HeatSa7dan,
};
const model = {
  id: 6,
  name: "model",
  ModelL1: ModelL1,
  ModelL2: ModelL2,
  ModelL3: ModelL3,
  ModelL4: ModelL4,
  ModelOldQ: ModelOldQ,
  Model2025Q: Model2025Q,
  ModelSa7dan: ModelSa7dan,
  ModelMarks: ModelMarks1,
};
const eco = {
  id: 7,
  name: "eco",
  Eco2025Q: Eco2025Q,
  EcoMarks: EcoMarks1,
  EcoOldQ: EcoOldQ,
};
const lab3b = {
  id: 8,
  name: "lab3b",
  Shell: Shell,
  LD: LD,
  LT: LT,
  CSTRSeries: CSTRSeries,
  SingleCSTR: SingleCSTR,
  Tubular: Tubular,
  Laminar: Laminar,
  LabMarks: LabMarks1,
};
const plant = {
  id: 9,
  name: "plant",
  Plant2025Q: Plant2025Q,
  PlantMarks: PlantMarks1,
};
export { unit, reactor, lab3a, industry, heat, model, plant, lab3b, eco };
